apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace:  prod-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume       # <-- Mount the ConfigMap here
              mountPath: /etc/nginx/conf.d/default.conf   # <-- Path where nginx expects config
              subPath: default.conf
              readOnly: true
            - name: nginx-html-volume
              mountPath: /usr/share/nginx/html
              readOnly: true  
              
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config 
            items:
              - key: default.conf
                path: default.conf
        - name: nginx-html-volume
          configMap:
            name: nginx-config
            items:
              - key: index.html
                path: index.html
              - key: hemanth.html
                path: hemanth.html         
