apiVersion: v1
kind: Service
metadata:
  name:  prod-nginx
  namespace:  prod-nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type:  ClusterIP
